baseURL = 'https://howardhu.me/'
languageCode = 'en-us'
title = 'Howard Hu'
theme = "smol"


# Parameters
[params]
    subtitle = "Your blog subtitle goes here!"
    dateFmt = "2006-01-02"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/howdhu"
        weight = 1 

    [[menu.footer]]
        name = "Mastodon"
        url = "https://mastodon.social/@howardhu"
        weight = 2 
        
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true